In [3]:
from sklearn.neighbors import KNeighborsClassifier
import numpy as np

In [4]:
raw_x=[[3,2],
       [3,1],
       [1,3],
       [3,4],
       [2,2],
       [7,4],
       [5,3],
       [9,2],
       [7,3],
       [7,0]
      ]
raw_y=[0,0,0,0,0,1,1,1,1,1]
X_train=np.array(raw_x)
y_train=np.array(raw_y)
x = np.array([8,3])

In [2]:
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [5]:
kNN_classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

In [7]:
X_predict = x.reshape(1,-1) # scikit-learn 预测需要包装成矩阵
kNN_classifier.predict(X_predict)

array([1])

In [10]:
X_predict
x

array([[8, 3]])

array([8, 3])

In [8]:
y_predict = kNN_classifier.predict(X_predict)

In [9]:
y_predict

array([1])

测试自己封装的类似于scikit-learn的knn模块

In [11]:
%run kNNClassifier.py

In [12]:
kNN_c = kNNClassifier(k=6)

In [13]:
kNN_c.fit(X_train, y_train)

KNN(k=6)

In [14]:
y_predict = kNN_c.predict(X_predict)

In [15]:
y_predict

array([1])

In [16]:
y_predict[0]

1